### ISSUE TITLE
switch to cryptography since pycrypto is unmaintained and vuln

### ISSUE THREAD

**Issue by nikster2** [freshprince/weechat-fish#25]
I was unable to get it to work with python 3.8. But with a few alterations it works for me.

First I got

           │08:15:04 weechat     | python: registered script "fish", version 0.10 (FiSH for weechat)
           │08:15:37 weechat     | python: stdout/stderr (fish): Traceback (most recent call last):
           │08:15:37 weechat     | python: stdout/stderr (fish):   File "/home/nik/.weechat/python/autoload/fish.py", line 792, in fish_modifier_out_privmsg_cb
           │08:15:37 weechat     | python: stdout/stderr (fish):     b = Blowfish(fish_keys[targetl])
           │08:15:37 weechat     | python: stdout/stderr (fish):   File "/home/nik/.weechat/python/autoload/fish.py", line 198, in __init__
           │08:15:37 weechat     | python: stdout/stderr (fish):     self.blowfish = Crypto.Cipher.Blowfish.new(key)
           │08:15:37 weechat     | python: stdout/stderr (fish): TypeError: new() missing 1 required positional argument: 'mode'

Which i fixed with "self.blowfish = Crypto.Cipher.Blowfish.new(key, Crypto.Cipher.Blowfish.MODE_ECB)"

Then I got the following error:

08:16:32 weechat     | python: stdout/stderr (fish):   File "/home/nik/.weechat/python/autoload/fish.py", line 792, in fish_modifier_out_privmsg_cb
           │08:16:32 weechat     | python: stdout/stderr (fish):     b = Blowfish(fish_keys[targetl])
           │08:16:32 weechat     | python: stdout/stderr (fish):   File "/home/nik/.weechat/python/autoload/fish.py", line 198, in __init__
           │08:16:32 weechat     | python: stdout/stderr (fish):     self.blowfish = Crypto.Cipher.Blowfish.new(key, Crypto.Cipher.Blowfish.MODE_ECB)
           │08:16:32 weechat     | python: stdout/stderr (fish):   File "/usr/lib/python3.8/site-packages/Crypto/Cipher/Blowfish.py", line 146, in new
           │08:16:32 weechat     | python: stdout/stderr (fish):     return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
           │08:16:32 weechat     | python: stdout/stderr (fish):   File "/usr/lib/python3.8/site-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
           │08:16:32 weechat     | python: stdout/stderr (fish):     return modes[mode](factory, **kwargs)
           │08:16:32 weechat     | python: stdout/stderr (fish):   File "/usr/lib/python3.8/site-packages/Crypto/Cipher/_mode_ecb.py", line 215, in _create_ecb_cipher
           │08:16:32 weechat     | python: stdout/stderr (fish):     cipher_state = factory._create_base_cipher(kwargs)
           │08:16:32 weechat     | python: stdout/stderr (fish):   File "/usr/lib/python3.8/site-packages/Crypto/Cipher/Blowfish.py", line 77, in _create_base_cipher
           │08:16:32 weechat     | python: stdout/stderr (fish):     result = start_operation(c_uint8_ptr(key),
           │08:16:32 weechat     | python: stdout/stderr (fish):   File "/usr/lib/python3.8/site-packages/Crypto/Util/_raw_api.py", line 144, in c_uint8_ptr
           │08:16:32 weechat     | python: stdout/stderr (fish):     raise TypeError("Object type %s cannot be passed to C code" % type(data))
           │08:16:32 weechat     | python: stdout/stderr (fish): TypeError: Object type <class 'str'> cannot be passed to C code

This i fixed by doing : "key = key.encode('iso8859-1')"

Now everything seems to work. 

I'm not really any good at Python, so there is probably better solution :)

**Comment by freshprince** [comment]
Hey nikster2

It seems like you are using an old version of Python Cryptography Toolkit. Could you try to upgrade and then try again?

**Comment by nikster2** [comment]
I'm running the latest version of this :

https://pypi.org/project/cryptography/

**Comment by nikster2** [comment]
pycrypto has been removed from my linux distribution since it's no longer maintained.

**Comment by freshprince** [comment]
You'll need this one: https://pypi.org/project/pycrypto/

There's no dependency to cryptography in fish.py

**Comment by nikster2** [comment]
pycrypto has not been updated since 2013 (and deemed unsafe). So guess I'll continue to use cryptography since it's maintained and gives the same functionality (albeit with some lesser changes). So do what you will with my "issue" :) Since it works for me with these small changes I'm satisfied.

**Comment by freshprince** [comment]
allright.
can you provide some links where pycrypto is deemed unsafe? maybe i'll make a switch if it makes sense.

**Comment by nikster2** [comment]
There is much to find if you search for "pycrypt unsafe" in google. Here is an example.

https://theartofmachinery.com/2017/02/02/dont_use_pycrypto.html

**Comment by mumixam** [comment]
https://github.com/Legrandin/pycryptodome/

is the naturally solution. its still updated and is a drop in (mostly) replacement for pycrypto

**Comment by mumixam** [comment]
https://github.com/Legrandin/pycryptodome/

its still updated and is a drop in (mostly) replacement for pycrypto

**Comment by freshprince** [comment]
current master should now work fine with pycryptodome
